/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './index.html',
        './src/**/*.{js,ts,jsx,tsx}',
    ],
    theme: {
        extend: {
            colors: {
                // Legacy / Primitive colors
                primary: {
                    50: '#f0fdfa',
                    100: '#ccfbf1',
                    200: '#99f6e4',
                    300: '#5eead4',
                    400: '#2dd4bf',
                    500: '#14b8a6',
                    600: '#0d9488',
                    700: '#0f766e',
                    800: '#115e59',
                    900: '#134e4a',
                },
                accent: {
                    50: '#fff7ed',
                    100: '#ffedd5',
                    200: '#fed7aa',
                    300: '#fdba74',
                    400: '#fb923c',
                    500: '#f97316',
                    600: '#ea580c',
                    700: '#c2410c',
                    800: '#9a3412',
                    900: '#7c2d12',
                },
                // Semantic & New Obsidian System (Flat structure for reliable build)
                'surface-card': '#ffffff',
                'surface-hover': '#f8fafc',
                'surface-border': '#e2e8f0', // Critical for border-surface-border
                'surface-muted': '#94a3b8',
                "inverse-primary": "#006a6a",
                "inverse-surface": "#e5e2e1",
                "outline-variant": "#3e4949",
                "surface-variant": "#353534",
                "secondary-fixed": "#ffdcc3",
                "on-primary-container": "#e3fffe",
                "on-surface-variant": "#bdc9c8",
                "surface-container-low": "#1c1b1b",
                "secondary-fixed-dim": "#ffb77d",
                "surface": "#131313",
                "on-secondary": "#4d2600",
                "on-secondary-fixed-variant": "#6e3900",
                "surface-container-highest": "#353534",
                "secondary-container": "#fd8b00",
                "on-tertiary": "#003734",
                "error-container": "#93000a",
                "on-error": "#690005",
                "tertiary-fixed": "#79f6ed",
                "outline": "#879392",
                "tertiary-container": "#00817b",
                "primary-fixed-dim": "#76d6d5",
                "error": "#ffb4ab",
                "on-tertiary-fixed-variant": "#00504c",
                "surface-dim": "#131313",
                "tertiary": "#59dad1",
                "on-secondary-container": "#603100",
                "on-tertiary-fixed": "#00201e",
                "primary-container": "#008080",
                "on-error-container": "#ffdad6",
                "surface-container": "#201f1f",
                "tertiary-fixed-dim": "#59dad1",
                "surface-container-high": "#2a2a2a",
                "on-background": "#e5e2e1",
                "on-secondary-fixed": "#2f1500",
                "background": "#131313",
                "surface-tint": "#76d6d5",
                "on-tertiary-container": "#e7fffc",
                "on-primary-fixed": "#002020",
                "on-surface": "#e5e2e1",
                "inverse-on-surface": "#313030",
                "on-primary": "#003737",
                "on-primary-fixed-variant": "#004f4f",
                "primary-fixed": "#93f2f2",
                "surface-container-lowest": "#0e0e0e",
                "surface-bright": "#393939"
            },
            borderRadius: {
                card: '16px',
                btn: '10px',
            },
            boxShadow: {
                card: '0 4px 24px 0 rgba(0,0,0,0.07)',
                'card-hover': '0 8px 32px 0 rgba(0,0,0,0.12)',
                toast: '0 8px 24px 0 rgba(0,0,0,0.15)',
            },
            fontFamily: {
                sans: ['Inter', 'system-ui', 'sans-serif'],
                headline: ['Manrope', 'sans-serif'],
                body: ['Inter', 'sans-serif'],
            },
            animation: {
                'fade-in': 'fadeIn 0.3s ease-out',
                'slide-up': 'slideUp 0.3s ease-out',
                'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
                'spin-slow': 'spin 3s linear infinite',
            },
            keyframes: {
                fadeIn: { from: { opacity: 0 }, to: { opacity: 1 } },
                slideUp: { from: { opacity: 0, transform: 'translateY(12px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
                pulseSoft: { '0%,100%': { opacity: 1 }, '50%': { opacity: 0.6 } },
            },
        },
    },
    plugins: [],
};
